# Generated by Django 4.2.2 on 2023-06-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('photos', models.JSONField()),
                ('phone', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
